preprocessing:
 stopwords:   ["check against delivery",  "check delivery",  "introduction", "video recording", "as delivered", "version as delivered", "distinguished", "mr", "mrs", "mr.", "mrs.", "ms.", "ms", "sir", "madam", "madame", "chairman", "chairmen", "chairwoman", "chairwomen", "chairperson", "chairpeople", "excellency", "excellencies", "majesty", "majesties", "highness", "highnesses", "royal", "honorable", "president", "king", "prince", "queen", "princess", "delegate", "delegates", "gentlemen", "ladies", "lady", "gentleman", "ministers", "'s", "also", "must", "would", "also", "refugee", "refugees", "unhcr", "united_nations", "united", "nations", "country", "year", "ha", "wa", "high_commissioner", "high", "commissioner",  "de", "la", "un", "en", "los", "el", "que"]
 punctuation:   [',', '.', ';', ':', '?', '!', '/', '-', '--', '(', ')', '–', '``' , ' ', '*']
 ngrams:
    min: 1
    max: 3
 df:
    min: 3
    max: 0.8
lda: 
 passes:   50
 iterations:   500
 num_topics:   10
